---
sidebar: sidebar 
permalink: anthos/anthos-solution-overview.html 
keywords: NVA-1165, Anthos, GKE, Netapp, Trident 
summary: Dieses Referenzdokument bietet eine Bereitstellungsvalidierung der Anthos-Lösung mit NetApp , die in mehreren Rechenzentrumsumgebungen bereitgestellt wird und von NetApp und unseren Engineering-Partnern validiert wurde. 
---
= NVA-1165: Anthos mit NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Banu Sundhar und Suresh Thoppay, NetApp

[role="lead"]
Dieses Referenzdokument bietet eine Bereitstellungsvalidierung der Anthos-Lösung mit NetApp durch NetApp und unsere Engineering-Partner, wenn sie in mehreren Rechenzentrumsumgebungen bereitgestellt wird.  Darüber hinaus wird die Speicherintegration mit NetApp Speichersystemen durch die Verwendung des Trident -Speicherorchestrators für die Verwaltung des persistenten Speichers detailliert beschrieben.  Abschließend untersuchen und dokumentieren wir eine Reihe von Lösungsvalidierungen und Anwendungsfällen aus der Praxis.



[[use-cases]]
== Anwendungsfälle

Die Lösung Anthos with NetApp ist so konzipiert, dass sie Kunden mit den folgenden Anwendungsfällen einen außergewöhnlichen Mehrwert bietet:

* Einfache Bereitstellung und Verwaltung der Anthos-Umgebung mithilfe der bereitgestellten `bmctl` Werkzeug auf blankem Metall oder `gkectl` Tool auf VMware vSphere.
* Kombinierte Leistung von Enterprise-Containern und virtualisierten Workloads mit Anthos, virtuell bereitgestellt auf vSphere oder auf Bare Metal mit https://cloud.google.com/anthos/clusters/docs/bare-metal/1.9/how-to/vm-workloads["kubevirt"^] .
* Reale Konfigurationen und Anwendungsfälle, die die Anthos-Funktionen bei Verwendung mit NetApp -Speicher und Trident, dem Open-Source-Speicherorchestrator für Kubernetes, hervorheben.




[[business-value]]
== Geschäftswert

Unternehmen wenden zunehmend DevOps-Praktiken an, um neue Produkte zu entwickeln, Release-Zyklen zu verkürzen und schnell neue Funktionen hinzuzufügen.  Aufgrund ihrer von Natur aus agilen Natur spielen Container und Microservices eine entscheidende Rolle bei der Unterstützung von DevOps-Praktiken.  Die Umsetzung von DevOps im Produktionsmaßstab in einer Unternehmensumgebung bringt jedoch eigene Herausforderungen mit sich und stellt bestimmte Anforderungen an die zugrunde liegende Infrastruktur, beispielsweise die folgenden:

* Hohe Verfügbarkeit auf allen Ebenen des Stacks
* Einfache Bereitstellungsverfahren
* Unterbrechungsfreier Betrieb und Upgrades
* API-gesteuerte und programmierbare Infrastruktur, um mit der Agilität von Microservices Schritt zu halten
* Mandantenfähigkeit mit Leistungsgarantien
* Die Möglichkeit, virtualisierte und containerisierte Workloads gleichzeitig auszuführen
* Die Fähigkeit, die Infrastruktur unabhängig von den Arbeitslastanforderungen zu skalieren


Die Lösung Anthos mit NetApp berücksichtigt diese Herausforderungen und bietet eine Lösung, die bei der Bewältigung aller Probleme hilft, indem sie die vollständig automatisierte Bereitstellung von Anthos vor Ort in der Rechenzentrumsumgebung der Wahl des Kunden implementiert.



[[technology-overview]]
== Technologieübersicht

Die Anthos-Lösung mit NetApp besteht aus den folgenden Hauptkomponenten:



[[anthos-on-prem]]
=== Anthos vor Ort

Anthos On Prem ist eine vollständig unterstützte Kubernetes-Plattform für Unternehmen, die im VMware vSphere-Hypervisor oder auf einer Bare-Metal-Infrastruktur Ihrer Wahl bereitgestellt werden kann.

Weitere Informationen zu Anthos finden Sie auf der Anthos-Website unter https://cloud.google.com/anthos["hier,"^] .



[[netapp-storage-systems]]
=== NetApp Speichersysteme

NetApp verfügt über mehrere Speichersysteme, die sich perfekt für Unternehmensrechenzentren und Hybrid-Cloud-Bereitstellungen eignen.  Das NetApp Portfolio umfasst NetApp ONTAP, Cloud Volumes ONTAP, Google Cloud NetApp Volumes, Azure NetApp Files und FSx ONTAP für NetApp ONTAP -Speichersysteme, die alle persistenten Speicher für containerisierte Anwendungen bereitstellen können.

Weitere Informationen sind unter link:https://www.netapp.com["NetApp Website"^] verfügbar.



[[netapp-storage-integrations]]
=== NetApp Storage-Integrationen

Trident ist ein Open-Source- und vollständig unterstützter Speicherorchestrator für Container und Kubernetes-Distributionen, einschließlich Anthos.

Weitere Informationen sind unter link:https://docs.netapp.com/us-en/trident/index.html["Trident Dokumentation"^] verfügbar.



[[advanced-configuration-options]]
== Erweiterte Konfigurationsoptionen

Dieser Abschnitt befasst sich mit Anpassungen, die reale Benutzer wahrscheinlich vornehmen müssen, wenn sie diese Lösung in der Produktion einsetzen, wie etwa das Erstellen eines dedizierten privaten Image-Registers oder das Bereitstellen benutzerdefinierter Load Balancer-Instanzen.



[[current-support-matrix-for-validated-releases]]
== Aktuelle Support-Matrix für validierte Releases

Siehe link:https://cloud.google.com/anthos/docs/resources/partner-storage#netapp["Anthos Speicherpartner Supportmatrix"^] die Liste der validierten Releases.
