---
sidebar: sidebar 
permalink: anthos/anthos-trident-ontap-iscsi.html 
summary: Um die Trident -Integration mit dem NetApp ONTAP Speichersystem zu ermöglichen, müssen Sie ein Backend erstellen, das die Kommunikation mit dem Speichersystem ermöglicht. 
keywords: Trident, Trident, ONTAP, AFF, FAS, iSCSI 
---
= NetApp ONTAP iSCSI-Konfiguration
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Um die Trident -Integration mit dem NetApp ONTAP Speichersystem zu ermöglichen, müssen Sie ein Backend erstellen, das die Kommunikation mit dem Speichersystem ermöglicht.

. Im heruntergeladenen Installationsarchiv im `sample-input` Ordnerhierarchie.  Für NetApp ONTAP -Systeme, die iSCSI bedienen, kopieren Sie die `backend-ontap-san.json` Datei in Ihr Arbeitsverzeichnis und bearbeiten Sie die Datei.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ cp sample-input/backends-samples/ontap-san/backend-ontap-san.json ./
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ vi backend-ontap-san.json
----
. Bearbeiten Sie die Werte „managementLIF“, „dataLIF“, „svm“, „username“ und „password“ in dieser Datei.
+
[listing]
----
{
  "version": 1,
  "storageDriverName": "ontap-san",
  "managementLIF": "172.21.224.201",
  "dataLIF": "10.61.181.240",
  "svm": "trident_svm",
  "username": "admin",
  "password": "password"
}
----
. Führen Sie mit dieser Backend-Datei den folgenden Befehl aus, um Ihr erstes Backend zu erstellen.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ ./tridentctl -n trident create backend -f backend-ontap-san.json
+------------------------+----------------+--------------------------------------+--------+---------+
|          NAME          | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+------------------------+----------------+--------------------------------------+--------+---------+
| ontapsan_10.61.181.241 | ontap-san      | 6788533c-7fea-4a35-b797-fb9bb3322b91 | online |       0 |
+------------------------+----------------+--------------------------------------+--------+---------+
----
. Nachdem das Backend erstellt wurde, müssen Sie als Nächstes eine Speicherklasse erstellen.  Genau wie beim Backend gibt es im Ordner „sample-inputs“ eine Beispiel-Speicherklassendatei, die für die Umgebung bearbeitet werden kann.  Kopieren Sie es in das Arbeitsverzeichnis und nehmen Sie die erforderlichen Änderungen vor, um das erstellte Backend widerzuspiegeln.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ cp sample-input/storage-class-samples/storage-class-csi.yaml.templ ./storage-class-basic.yaml
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ vi storage-class-basic.yaml
----
. Die einzige Änderung, die an dieser Datei vorgenommen werden muss, ist die Definition der `backendType` Wert auf den Namen des Speichertreibers aus dem neu erstellten Backend.  Beachten Sie auch den Wert des Namensfelds, auf den in einem späteren Schritt verwiesen werden muss.
+
[listing]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: basic-csi
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-san"
----
+

NOTE: Es gibt ein optionales Feld namens `fsType` das in dieser Datei definiert ist.  In iSCSI-Backends kann dieser Wert auf einen bestimmten Linux-Dateisystemtyp (XFS, ext4 usw.) festgelegt oder gelöscht werden, damit das Betriebssystem des Worker-Knotens entscheiden kann, welches Dateisystem verwendet werden soll.

. Führen Sie den `kubectl` Befehl zum Erstellen der Speicherklasse.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ kubectl create -f storage-class-basic.yaml
storageclass.storage.k8s.io/basic-csi created
----
. Nachdem Sie die Speicherklasse erstellt haben, müssen Sie den ersten Persistent Volume Claim (PVC) erstellen.  Es gibt eine Probe `pvc-basic.yaml` Datei, die zum Ausführen dieser Aktion verwendet werden kann und sich ebenfalls in den Beispieleingaben befindet.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ cp sample-input/pvc-samples/pvc-basic.yaml ./
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ vi pvc-basic.yaml
----
. Die einzige Änderung, die an dieser Datei vorgenommen werden muss, besteht darin, sicherzustellen, dass die `storageClassName` Das Feld entspricht dem gerade erstellten.  Die PVC-Definition kann je nach Bedarf der bereitzustellenden Arbeitslast weiter angepasst werden.
+
[listing]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: basic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic-csi
----
. Erstellen Sie den PVC, indem Sie die `kubectl` Befehl.  Die Erstellung kann je nach Größe des zu erstellenden Sicherungsvolumes einige Zeit in Anspruch nehmen. Sie können den Vorgang daher während des Abschlusses verfolgen.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ kubectl create -f pvc-basic.yaml
persistentvolumeclaim/basic created

[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ kubectl get pvc
NAME    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
basic   Bound    pvc-7ceac1ba-0189-43c7-8f98-094719f7956c   1Gi        RWO            basic-csi      3s
----

