---
sidebar: sidebar 
permalink: anthos/anthos-seesaw-lb.html 
summary: Auf dieser Seite finden Sie detaillierte Installations- und Konfigurationsanweisungen für den SeeSaw-Lastenausgleich. 
keywords: Anthos, GKE, Kubernetes, SeeSaw, LoadBalancer 
---
= Installieren von SeeSaw-Load Balancern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Auf dieser Seite finden Sie die Installations- und Konfigurationsanweisungen für den verwalteten Lastenausgleich von SeeSaw.

Seesaw ist der standardmäßig verwaltete Netzwerk-Load Balancer, der in einer Anthos-Cluster-Umgebung auf VMware von Version 1.6 bis 1.10 installiert ist.



[[installing-the-seesaw-load-balancer]]
== Installieren des SeeSaw-Lastenausgleichs

Der SeeSaw-Load Balancer ist vollständig in Anthos-Cluster auf VMware integriert und verfügt über eine automatisierte Bereitstellung als Teil der Admin- und Benutzercluster-Setups.  Es gibt Textblöcke in der `cluster.yaml` Konfigurationsdateien, die geändert werden müssen, um Load Balancer-Informationen bereitzustellen, und dann gibt es einen zusätzlichen Schritt vor der Clusterbereitstellung, um den Load Balancer mithilfe der integrierten `gkectl` Werkzeug.


NOTE: SeeSaw-Lastverteiler können im HA- oder Nicht-HA-Modus bereitgestellt werden.  Für diese Validierung wurde der SeeSaw-Load Balancer im Nicht-HA-Modus bereitgestellt, was die Standardeinstellung ist.  Für Produktionszwecke empfiehlt NetApp die Bereitstellung von SeeSaw in einer HA-Konfiguration, um Fehlertoleranz und Zuverlässigkeit zu gewährleisten.



[[integration-with-anthos]]
== Integration mit Anthos

In jeder Konfigurationsdatei gibt es einen Abschnitt für den Administratorcluster und in jedem Benutzercluster, den Sie bereitstellen möchten, um den Load Balancer so zu konfigurieren, dass er von Anthos On-Prem verwaltet wird.

Der folgende Text ist ein Beispiel aus der Konfiguration der Partition für den GKE-Admin-Cluster.  Die Werte, die auskommentiert und geändert werden müssen, sind unten fettgedruckt:

[listing, subs="+quotes,+verbatim"]
----
*loadBalancer:*
  # (Required) The VIPs to use for load balancing
  *vips:*
    # Used to connect to the Kubernetes API
    *controlPlaneVIP: "10.61.181.230"*
    # # (Optional) Used for admin cluster addons (needed for multi cluster features). Must
    # # be the same across clusters
    # # addonsVIP: ""
  # (Required) Which load balancer to use "F5BigIP" "Seesaw" or "ManualLB". Uncomment
  # the corresponding field below to provide the detailed spec
  *kind: Seesaw*
  # # (Required when using "ManualLB" kind) Specify pre-defined nodeports
  # manualLB:
  #   # NodePort for ingress service's http (only needed for user cluster)
  #   ingressHTTPNodePort: 0
  #   # NodePort for ingress service's https (only needed for user cluster)
  #   ingressHTTPSNodePort: 0
  #   # NodePort for control plane service
  #   controlPlaneNodePort: 30968
  #   # NodePort for addon service (only needed for admin cluster)
  #   addonsNodePort: 31405
  # # (Required when using "F5BigIP" kind) Specify the already-existing partition and
  # # credentials
  # f5BigIP:
  #   address:
  #   credentials:
  #     username:
  #     password:
  #   partition:
  #   # # (Optional) Specify a pool name if using SNAT
  #   # snatPoolName: ""
  # (Required when using "Seesaw" kind) Specify the Seesaw configs
  *seesaw:*
  # (Required) The absolute or relative path to the yaml file to use for IP allocation
  #  for LB VMs. Must contain one or two IPs.
  *ipBlockFilePath: "admin-seesaw-block.yaml"*
  #   (Required) The Virtual Router IDentifier of VRRP for the Seesaw group. Must
  #   be between 1-255 and unique in a VLAN.
    *vrid: 100*
  #   (Required) The IP announced by the master of Seesaw group
    *masterIP: "10.61.181.236"*
  #   (Required) The number CPUs per machine
    *cpus: 1*
  #   (Required) Memory size in MB per machine
    *memoryMB: 2048*
  #   (Optional) Network that the LB interface of Seesaw runs in (default: cluster
  #   network)
    *vCenter:*
  #   vSphere network name
      *networkName: VM_Network*
  #   (Optional) Run two LB VMs to achieve high availability (default: false)
    *enableHA: false*
----
Der SeeSaw Load Balancer verfügt außerdem über eine separate statische `seesaw-block.yaml` Datei, die Sie für jede Clusterbereitstellung bereitstellen müssen.  Diese Datei muss sich im selben Verzeichnis befinden wie die `cluster.yaml` Bereitstellungsdatei oder der vollständige Pfad muss im obigen Abschnitt angegeben werden.

Eine Probe der `admin-seesaw-block.yaml` Die Datei sieht wie das folgende Skript aus:

[listing, subs="+quotes,+verbatim"]
----
blocks:
  - netmask: "255.255.255.0"
    gateway: "10.63.172.1"
    ips:
    - ip: "10.63.172.152"
      hostname: "admin-seesaw-vm"
----

NOTE: Diese Datei enthält das Gateway und die Netzmaske für das Netzwerk, das der Load Balancer dem zugrunde liegenden Cluster bereitstellt, sowie die Verwaltungs-IP und den Hostnamen für die virtuelle Maschine, die zum Ausführen des Load Balancers bereitgestellt wird.
