---
sidebar: sidebar 
permalink: videos/tanzu-videos.html 
keywords: video, demonstration, deployment, VMware Tanzu with NetApp, NetApp, Tanzu 
summary: Diese Seite enthält Links zu Videos, die einige der in diesem Dokument beschriebenen Funktionen demonstrieren. 
---
= Sehen Sie sich Videos zu VMware Tanzu mit NetApp an
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Entdecken Sie die Integration von VMware Tanzu mit NetApp anhand einer Reihe von Videos, die wichtige Funktionen wie die Bereitstellung persistenter Speicher, das Klonen von Anwendungen und den Datenschutz mit Trident demonstrieren.


NOTE: Diese Demos wurden als technische Vorschau mit Version 1.3.1 von TKG und Version 21.12 von Trident Protect aufgezeichnet.  Informationen zu offiziell unterstützten Versionen finden Sie in der Support-Matrix.



== Bereitstellung von persistentem Speicher

.Verwenden Sie Trident , um persistenten Speicher in VMware Tanzu bereitzustellen – VMware Tanzu mit NetApp
video::8db3092b-3468-4754-b2d7-b01200fbb38d[panopto,width=360]


== Anwendungsklonen und Datenschutz

.Verwenden Sie Trident Protect, um Anwendungen in VMWare Tanzu zu klonen – VMware Tanzu mit NetApp
video::01aff358-a0a2-4c4f-9062-b01200fb9abd[panopto,width=360]