---
sidebar: sidebar 
permalink: openshift/os-adv-mgmt-deployment-prereq.html 
keywords: OpenShift, OCP, Trident, NetApp ONTAP, ONTAP, Trident, Red Hat OpenShift, Advanced Cluster Management, Advanced Cluster Management for Kubernetes 
summary: Erweitertes Cluster-Management für Kubernetes auf Red Hat OpenShift mit NetApp 
---
= Bereitstellen der erweiterten Clusterverwaltung für Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dieser Abschnitt behandelt die erweiterte Clusterverwaltung für Kubernetes auf Red Hat OpenShift mit NetApp.



[[prerequisites]]
== Voraussetzungen

. Ein Red Hat OpenShift-Cluster (höher als Version 4.5) für den Hub-Cluster
. Red Hat OpenShift-Cluster (höher als Version 4.4.3) für verwaltete Cluster
. Cluster-Admin-Zugriff auf den Red Hat OpenShift-Cluster
. Ein Red Hat-Abonnement für Advanced Cluster Management für Kubernetes


Advanced Cluster Management ist ein Add-on für den OpenShift Cluster, daher gelten bestimmte Anforderungen und Einschränkungen hinsichtlich der Hardware-Ressourcen, abhängig von den im Hub und in den verwalteten Clustern genutzten Funktionen. Diese Aspekte sind bei der Dimensionierung der Cluster zu berücksichtigen. Siehe link:https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.2/html-single/install/index#network-configuration["Anforderungen an die Netzwerkkonfiguration"^] für weitere Details.

Optional: Falls der Hub-Cluster dedizierte Knoten für die Infrastrukturkomponenten besitzt und die Ressourcen für Advanced Cluster Management nur auf diesen Knoten installiert werden sollen, müssen diesen Knoten entsprechend Tolerations und Selektoren hinzugefügt werden. Weitere Details finden sich unter link:https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.2/html/install/installing#installing-on-infra-node["Installation auf Infrastrukturknoten"^].
