---
sidebar: sidebar 
permalink: openshift/os-trident-element-iscsi.html 
summary:  
keywords: Trident, Element, Solidfire, iSCSI 
---
= NetApp Element iSCSI-Konfiguration
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Um die Trident Integration mit dem NetApp Element -Speichersystem zu ermöglichen, müssen Sie ein Backend erstellen, das die Kommunikation mit dem Speichersystem über das iSCSI-Protokoll ermöglicht.

. Im heruntergeladenen Installationsarchiv im `sample-input` Ordnerhierarchie.  Für NetApp Element -Systeme, die iSCSI bereitstellen, kopieren Sie die `backend-solidfire.json` Datei in Ihr Arbeitsverzeichnis und bearbeiten Sie die Datei.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ cp sample-input/backends-samples/solidfire/backend-solidfire.json ./
[netapp-user@rhel7 trident-installer]$ vi ./backend-solidfire.json
----
+
.. Bearbeiten Sie den Benutzer, das Passwort und den MVIP-Wert auf der `EndPoint` Linie.
.. Bearbeiten Sie die `SVIP` Wert.
+
[listing]
----
 {
    "version": 1,
    "storageDriverName": "solidfire-san",
    "Endpoint": "https://trident:password@172.21.224.150/json-rpc/8.0",
    "SVIP": "10.61.180.200:3260",
    "TenantName": "trident",
    "Types": [{"Type": "Bronze", "Qos": {"minIOPS": 1000, "maxIOPS": 2000, "burstIOPS": 4000}},
              {"Type": "Silver", "Qos": {"minIOPS": 4000, "maxIOPS": 6000, "burstIOPS": 8000}},
              {"Type": "Gold", "Qos": {"minIOPS": 6000, "maxIOPS": 8000, "burstIOPS": 10000}}]
}
----


. Führen Sie mit dieser Back-End-Datei den folgenden Befehl aus, um Ihr erstes Back-End zu erstellen.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ ./tridentctl -n trident create backend -f backend-solidfire.json
+-------------------------+----------------+--------------------------------------+--------+---------+
|          NAME           | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+-------------------------+----------------+--------------------------------------+--------+---------+
| solidfire_10.61.180.200 | solidfire-san  | b90783ee-e0c9-49af-8d26-3ea87ce2efdf | online |       0 |
+-------------------------+----------------+--------------------------------------+--------+---------+
----
. Nachdem das Backend erstellt wurde, müssen Sie als Nächstes eine Speicherklasse erstellen.  Genau wie beim Backend gibt es im Ordner „sample-inputs“ eine Beispiel-Speicherklassendatei, die für die Umgebung bearbeitet werden kann.  Kopieren Sie es in das Arbeitsverzeichnis und nehmen Sie die erforderlichen Änderungen vor, um das erstellte Backend widerzuspiegeln.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ cp sample-input/storage-class-samples/storage-class-csi.yaml.templ ./storage-class-basic.yaml
[netapp-user@rhel7 trident-installer]$ vi storage-class-basic.yaml
----
. Die einzige Änderung, die an dieser Datei vorgenommen werden muss, ist die Definition der `backendType` Wert auf den Namen des Speichertreibers aus dem neu erstellten Backend.  Beachten Sie auch den Wert des Namensfelds, auf den in einem späteren Schritt verwiesen werden muss.
+
[listing]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: basic-csi
provisioner: csi.trident.netapp.io
parameters:
  backendType: "solidfire-san"
----
+

NOTE: Es gibt ein optionales Feld namens `fsType` das in dieser Datei definiert ist.  In iSCSI-Backends kann dieser Wert auf einen bestimmten Linux-Dateisystemtyp (XFS, ext4 usw.) festgelegt oder gelöscht werden, damit OpenShift entscheiden kann, welches Dateisystem verwendet werden soll.

. Führen Sie den `oc` Befehl zum Erstellen der Speicherklasse.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ oc create -f storage-class-basic.yaml
storageclass.storage.k8s.io/basic-csi created
----
. Nachdem Sie die Speicherklasse erstellt haben, müssen Sie den ersten Persistent Volume Claim (PVC) erstellen.  Es gibt eine Probe `pvc-basic.yaml` Datei, die zum Ausführen dieser Aktion verwendet werden kann und sich ebenfalls in den Beispieleingaben befindet.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ cp sample-input/pvc-samples/pvc-basic.yaml ./
[netapp-user@rhel7 trident-installer]$ vi pvc-basic.yaml
----
. Die einzige Änderung, die an dieser Datei vorgenommen werden muss, besteht darin, sicherzustellen, dass die `storageClassName` Das Feld entspricht dem gerade erstellten.  Die PVC-Definition kann je nach Bedarf der bereitzustellenden Arbeitslast weiter angepasst werden.
+
[listing]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: basic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic-csi
----
. Erstellen Sie den PVC, indem Sie die `oc` Befehl.  Die Erstellung kann je nach Größe des zu erstellenden Sicherungsvolumes einige Zeit in Anspruch nehmen. Sie können den Vorgang daher während des Abschlusses verfolgen.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ oc create -f pvc-basic.yaml
persistentvolumeclaim/basic created

[netapp-user@rhel7 trident-installer]$ oc get pvc
NAME    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
basic   Bound    pvc-3445b5cc-df24-453d-a1e6-b484e874349d   1Gi        RWO            basic-csi      5s
----

